'use client'
import { useMemo, useState } from 'react'
import { Search, Plus, Database, ArrowLeft, PackageOpen } from 'lucide-react'
import { ProductCardPreview } from '@/components/studio/ProductCardPreview'
import { ProductForm } from '@/components/studio/ProductForm'
import { categories, brands, emptyProduct, seedProducts, type LogisticsProduct } from '@/types/catalog'

export default function CatalogStudioPage() {
  const [products, setProducts] = useState(seedProducts); const [selected, setSelected] = useState<LogisticsProduct>(seedProducts[0]); const [query, setQuery] = useState(''); const [brand, setBrand] = useState('הכל'); const [category, setCategory] = useState('הכל'); const [warehouse, setWarehouse] = useState('הכל');
  const filtered = useMemo(() => products.filter(p => (!query || `${p.officialName} ${p.sku} ${p.aliases.join(' ')}`.includes(query)) && (brand === 'הכל' || p.brand === brand) && (category === 'הכל' || p.category === category) && (warehouse === 'הכל' || p.warehouse === warehouse)), [products, query, brand, category, warehouse])
  function newProduct() { setSelected({ ...emptyProduct }); }
  function seed() { setProducts(seedProducts); setSelected(seedProducts[0]) }
  return <main dir="rtl" className="studio-shell"><header className="studio-header"><div><div className="brand-mark">SABAN <span>LOGISTICS</span></div><h1>סטודיו מוצרים <em>ומילון לוגיסטי</em></h1><p>מרכז ידע חי עבור נועה AI · ניהול קטלוג logistics_catalog</p></div><div className="header-actions"><button className="ghost-btn" onClick={seed}><Database /> טעינת מוצרי בסיס</button><button className="primary-btn" onClick={newProduct}><Plus /> הזנת מוצר חדש</button></div></header><div className="studio-grid"><aside className="preview-pane"><div className="pane-label"><span>תצוגה מקדימה חיה</span><span className="live-dot">LIVE</span></div><ProductCardPreview product={selected} /></aside><section className="editor-pane"><div className="toolbar"><div className="search-box"><Search /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="חיפוש לפי שם, מק״ט או סלנג..." /></div><select value={brand} onChange={e => setBrand(e.target.value)}>{brands.map(x => <option key={x}>{x === 'הכל' ? 'כל המותגים' : x}</option>)}</select><select value={category} onChange={e => setCategory(e.target.value)}>{categories.map(x => <option key={x}>{x === 'הכל' ? 'כל הקטגוריות' : x}</option>)}</select><select value={warehouse} onChange={e => setWarehouse(e.target.value)}><option value="הכל">כל המחסנים</option><option value="4_haresh">4 החרש</option><option value="1_talmid">1 התלמיד</option></select></div><div className="editor-content"><div className="product-list"><div className="list-heading"><b>מוצרים בקטלוג</b><span>{filtered.length} פריטים</span></div>{filtered.map(p => <button className={`product-row ${selected.sku === p.sku ? 'active' : ''}`} key={p.sku} onClick={() => setSelected(p)}><span className="row-icon"><PackageOpen /></span><span><b>{p.officialName}</b><small>{p.sku} · {p.brand}</small></span><ArrowLeft /></button>)}{!filtered.length && <p className="empty">לא נמצאו מוצרים</p>}</div><ProductForm product={selected} onChange={setSelected} onSaved={() => { if (!products.some(p => p.sku === selected.sku)) setProducts([...products, selected]) }} /></div></section></div></main>
}
