'use client'
import { useState } from 'react'
import { doc, setDoc } from 'firebase/firestore'
import { db } from '@/lib/firebase'
import type { LogisticsProduct } from '@/types/catalog'

export function ProductForm({ product, onChange, onSaved }: { product: LogisticsProduct; onChange: (p: LogisticsProduct) => void; onSaved: () => void }) {
  const [message, setMessage] = useState('')
  const update = (key: keyof LogisticsProduct, value: string | number | string[]) => onChange({ ...product, [key]: value })
  const field = (key: keyof LogisticsProduct, label: string, type = 'text', placeholder = '') => <label className="field"><span>{label}</span><input type={type} value={product[key] as string | number} placeholder={placeholder} onChange={e => update(key, type === 'number' ? Number(e.target.value) : e.target.value)} /></label>
  const tags = (key: 'approvedSubstrates' | 'mandatoryAddons' | 'aliases', label: string) => <label className="field"><span>{label} <small>הפרדה בפסיקים</small></span><input value={product[key].join(', ')} onChange={e => update(key, e.target.value.split(',').map(v => v.trim()).filter(Boolean))} /></label>
  async function save() { if (!product.sku || !product.officialName) { setMessage('יש למלא מק״ט ושם מוצר'); return } try { await setDoc(doc(db, 'logistics_catalog', product.sku), { ...product, updatedAt: new Date() }, { merge: true }); setMessage('המוצר נשמר בהצלחה'); onSaved() } catch { setMessage('לא ניתן לשמור. בדוק חיבור Firebase והרשאות Firestore.') } }
  return <div className="form-wrap"><section className="form-section"><h3>01 · מידע כללי ומסחרי</h3><div className="form-grid">{field('sku','מק״ט *')}{field('officialName','שם מוצר *')}{field('brand','מותג')}{field('category','קטגוריה')}{field('listPriceNis','מחירון ₪','number')}{field('contractorPriceNis','מחיר קבלן ₪','number')}{field('promoTag','תגית מבצע')}</div></section><section className="form-section"><h3>02 · לוגיסטיקה, משקלים ופקדונות</h3><div className="form-grid">{field('packagingUnit','יחידת אריזה')}{field('unitWeightKg','משקל יחידה ק״ג','number')}{field('unitsPerPallet','יחידות במשטח','number')}{field('palletDepositNis','פקדון משטח ₪','number')}<label className="field"><span>מחסן</span><select value={product.warehouse} onChange={e => update('warehouse', e.target.value as LogisticsProduct['warehouse'])}><option value="4_haresh">4 החרש</option><option value="1_talmid">1 התלמיד</option></select></label><label className="field"><span>משאית</span><select value={product.defaultTruck} onChange={e => update('defaultTruck', e.target.value as LogisticsProduct['defaultTruck'])}><option value="crane_mercedes">חכמת מנוף</option><option value="flatbed_isuzu">עלי חלוקה</option></select></label></div></section><section className="form-section"><h3>03 · מפרט טכני וביצוע בשטח</h3><div className="form-grid">{field('coverageM2','כושר כיסוי מ״ר','number')}{field('coverageNotes','הערת כיסוי')}{field('openTimeMinutes','זמן פתוח')}{field('dryingTimeHours','זמן ייבוש')}{field('applicationMethod','שיטת יישום')}{field('officialStandard','תקן רשמי')}{tags('approvedSubstrates','מצעים מאושרים')}</div></section><section className="form-section"><h3>04 · מוצרים משלימים ומדיה</h3><div className="form-grid">{tags('mandatoryAddons','מוצרים נלווים')}{tags('aliases','שמות נרדפים / סלנג')}{field('imageUrl','קישור תמונה')}{field('youtubeUrl','קישור YouTube')}{field('tdsUrl','קישור TDS')}</div></section><div className="form-actions"><button className="save-btn" onClick={save}>שמור ב-Firestore</button>{message && <span className={message.includes('בהצלחה') ? 'success' : 'error'}>{message}</span>}</div></div>
}
